name: aim_bi_project
channels:
    - conda-forge
dependencies:
  - black
  - flask
  - flask-cors
  - ipykernel
  - ipympl
  - matplotlib
  - numpy
  - pandas
  - pytz
  - requests
  #ToDo: - gunicorn